version: "3"
services:
  node:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - .:/backend/app
    env_file:
      - ./backend/.env
    # command: ["/bin/sh", "-c", "yarn install --production=false && yarn dev"]
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.5
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    # command: ["/bin/sh", "-c", "yarn install && yarn dev"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=homestead
      - MONGO_INITDB_ROOT_PASSWORD=secret

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/fronted/app
volumes:
  mongo:
networks:
  default:
    name: microservicenetwork
